spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://db:3306/popspot_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: test-secret-key-for-integration-tests-must-be-long-enough-256bits