spring:
  config:
    activate:
      on-profile: perf

  datasource:
    url: jdbc:mysql://localhost:3306/popspot_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    root: WARN
    com.back.popspot: WARN
    org.hibernate.SQL: "OFF"
    org.hibernate.orm.jdbc.bind: "OFF"

reservation:
  waitlist:
    enabled: false

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles: 0.5,0.95,0.99
