name: Checkstyle

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          tool_version: 9.3
          config_file: naver-checkstyle-rules.xml
